### ISSUE TITLE
Pull requests

### ISSUE THREAD

**Issue by tosterakakwapisz** [nukebot/discord-nuke-bot#10]
I'm sorry, but I'm complete newbie when it comes to creating pull requests. I wanted to update ur readme file. Use headings instead of bold text ect. and I cannot do that. Can u help me understand if it's my fault or it's just me not having correct permissions...

**Comment by TKperson** [comment]
You need to be a contributor or owner to edit any github repositories.
To make a pull request you will have to fork this repo. And it's better to find a video about it then asking this here.

**Comment by tosterakakwapisz** [comment]
Thanks! I did like you said. Expect a pull request soon :stuck_out_tongue:
